### PR TITLE
Float64.Add eligible for inlining with goto instead of for loop

### PR DESCRIPTION
**Pull request by temoto**
Before opening your pull request, please make sure that you've:

- [x] [signed Uber's Contributor License Agreement](https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform);
- [ ] added tests to cover your changes;
- [ ] run the test suite locally (`make test`); and finally,
- [ ] run the linters locally (`make lint`).

Thanks for your contribution!

### CODE REVIEW

**Comment by prashantv** [comment]
Thanks for your contribution @temoto 

I'd like to avoid complicating the code without some clear benefits, so ideally we'd want to see:
 - benchmark comparisons to see if there's an impactful difference
 - verification that this leads to inlined code

I'm not sure this will work since the Go compiler optimizations page calls out that inlining is disabled when complex features are used, and it includes loops as well as labels (which we're using for the goto here).

https://github.com/golang/go/wiki/CompilerOptimizations#function-inlining

> Only short and simple functions are inlined. To be inlined a function must contain less than ~40 expressions and does not contain complex things like function calls, loops, labels, closures, panic's, recover's, select's, switch'es, etc.

**Comment by temoto** [comment]
Yeah it may seem like unsupported dust. Copied this goto trick from pretty much same atomic float wrapper in my project, where I checked compiler output and was surprised to learn that `for` is a performance obstacle.

```
# before patch
./atomic.go:288:6: cannot inline (*Float64).Add: unhandled op FOR

# after patch
./atomic.go:288:6: can inline (*Float64).Add as: method(*Float64) func(float64) float64 { tryCAS: ; old := f.Load(); new := old + s; if f.CAS(old, new) { return new }; goto tryCAS }
./atomic.go:300:14: inlining call to (*Float64).Add method(*Float64) func(float64) float64 { tryCAS: ; old := f.Load(); new := old + s; if f.CAS(old, new) { return new }; goto tryCAS }
```

```
# benchcmp
benchmark                              old ns/op     new ns/op     delta
BenchmarkStress/f64/parallel-4         102           98.9          -3.04%
BenchmarkStress/f64/serial-4           45.1          44.7          -0.93%
BenchmarkStress/f64/add/serial-4       13.8          13.4          -2.61%
BenchmarkStress/f64/add/parallel-4     35.6          37.5          +5.11%
```

The f64/add code, I doubt it's useful to include:
```go
func stressFloat64Add() func() {
       var atom Float64
       return func() {
               atom.Add(1.1)
       }
}
```

**Comment by temoto** [comment]
@prashantv ping

**Comment by prashantv** [comment]
Thanks for the additional information @temoto

I was able to verify that `goto` causes the function to be inlined. I created a branch with both versions, where `AddLoop` uses the old way, while `Add` is using the goto.

We see that `AddLoop` has a function call:
```
     280ms      280ms     68a605: MOVSD_XMM $f64.3ff199999999999a(SB), X0 ;go.uber.org/atomic.stressFloat64AddLoop.func1 stress_test.go:65
         .          .     68a60d: MOVSD_XMM X0, 0x8(SP)                   ;stress_test.go:65
                                                                          ;go.uber.org/atomic.stressFloat64AddLoop.func1 stress_test.go:65
      10ms     26.43s     68a613: CALL go.uber.org/atomic.(*Float64).AddLoop(SB)
         .          .     68a618: MOVQ 0x18(SP), BP                       ;stress_test.go:66
```

On the other hand, `Add` does not:
```
     790ms      790ms     68a5ae: MOVSD_XMM $f64.3ff199999999999a(SB), X1 ;go.uber.org/atomic.(*Float64).Add atomic.go:291
         .          .     68a5b6: ADDSD X1, X0                            ;atomic.go:291
     1.35s     18.83s     68a5ba: NOPL                                    ;go.uber.org/atomic.(*Float64).Add atomic.go:292
         .      7.08s     68a5bb: NOPL                                    ;go.uber.org/atomic.(*Float64).Load atomic.go:279
         .          .     68a5bc: NOPL                                    ;atomic.go:316
         .      360ms     68a5bd: NOPL                                    ;go.uber.org/atomic.(*Float64).CAS atomic.go:316
     360ms      360ms     68a5be: MOVQ X0, BX                             ;math.Float64bits unsafe.go:23
     330ms      330ms     68a5c3: MOVQ DX, AX                             ;go.uber.org/atomic.(*Float64).CAS atomic.go:316
         .          .     68a5c6: LOCK CMPXCHGQ BX, 0(CX)                 ;atomic.go:316
    16.74s     16.74s     68a5cb: SETE DL                                 ;go.uber.org/atomic.(*Float64).CAS atomic.go:316
      50ms       50ms     68a5ce: TESTL DL, DL
         .          .     68a5d0: JE 0x68a5a5                             ;atomic.go:292

```

However, the results of the benchmark didn't really show any improvement,
```
BenchmarkStress/f64-add-loop/serial-4   1000000000               9.17 ns/op
BenchmarkStress/f64-add-loop/parallel-4                 100000000               73.2 ns/op
BenchmarkStress/f64-add/serial-4                        1000000000               9.36 ns/op
BenchmarkStress/f64-add/parallel-4                      100000000               72.3 ns/op
PASS
ok      go.uber.org/atomic      35.235s
```

I ran benchmarks with longer `benchtime` and saw the same -- the `AddLoop` was actually faster (in serial),
```
BenchmarkStress/f64-add/serial-4        3000000000               9.65 ns/op
BenchmarkStress/f64-add/parallel-4              500000000               76.0 ns/op
BenchmarkStress/f64-add-loop/serial-4           3000000000               9.53 ns/op
BenchmarkStress/f64-add-loop/parallel-4         500000000               77.0 ns/op
PASS
ok      go.uber.org/atomic      151.635s
```

I'm a little surprised that the inlining seems to have a slight negative impact when run serially.  The parallel benchmark varied -- sometimes the loop version was faster, sometimes the goto version was faster.

cc @abhinav for his thoughts

**Comment by temoto** [comment]
Yes I observed significant variation in benchmarks too, and it feels wrong.
Perhaps CPU cache is the reason, but I don't know how to verify that.

How did you get that assembly listing with timings?

**Comment by prashantv** [comment]
You can create a CPU profile using `-cpuprofile` and then use `go tool pprof` to view the profile. The `disasm` command will print the disassembly.

There's a few tutorials on the net on how to use pprof for profiling, including a [talk I've given in the past](https://www.youtube.com/watch?v=N3PWzBeLX2M).

**Pull request closed without merging**
